#!/bin/bash
# Go cross-compile 
# Usually, only the VERSION changes.
# The OSLIST and ARCHLIST can change, as well.
# No need to change anything below ####
# 

VERSION=0.2.1

TOOLNAME=rwctl
OSLIST=(linux darwin windows)
ARCHLIST=(amd64 386)

####

DISTDIR=dist/${VERSION}
mkdir -p ${DISTDIR}

echo "Compiling version ${VERSION}:"
for os in ${OSLIST[*]}; do
  for arch in ${ARCHLIST[*]}; do
  	EXT=""
  	if [[ ${os} == "windows" ]]; then
  		EXT=".exe"
  	fi
  	GOOS=${os}
  	GOARCH=${arch}
  	echo "Compiling ${GOOS}/${GOARCH}..."
  	OUTPUTFILE=${DISTDIR}/${TOOLNAME}-${VERSION}-${GOOS}.${GOARCH}${EXT}
    GOOS=${GOOS} GOARCH=${GOARCH} go build -o ${OUTPUTFILE} main.go
    file ${OUTPUTFILE}
  done
done
# for homebrew distribution, rename darwin.amd64, gz, shasum
mv ${DISTDIR}/${TOOLNAME}-${VERSION}-darwin.amd64 ${DISTDIR}/${TOOLNAME}
cd ${DISTDIR}
tar -czf ${TOOLNAME}-${VERSION}.tar.gz ${TOOLNAME}
shasum -a 256 ${TOOLNAME}-${VERSION}.tar.gz > ${TOOLNAME}-${VERSION}.tar.gz.shasum256
